// 服务端返回的错误码与客户端的分支判断此前各写一遍字符串，任一端的拼写
// 变化都不会引发编译错误。这里做唯一真相源：服务端构造响应用 ERROR_CODES，
// 客户端比较也用 ERROR_CODES，ApiError.code 收窄为 ErrorCode。
//
// 不含 EADDRINUSE、UND_ERR_CONNECT_TIMEOUT 这类系统/undici 错误码——它们
// 来自运行时而非本服务，只在 startup.ts 和 ai.ts 里做 instanceof 判断。
import { z } from "zod"

export const ERROR_CODES = {
  AI_ACTION_UNAVAILABLE: "AI_ACTION_UNAVAILABLE",
  AI_AUTH: "AI_AUTH",
  AI_CONFIRMATION_REQUIRED: "AI_CONFIRMATION_REQUIRED",
  AI_INVALID_ENDPOINT: "AI_INVALID_ENDPOINT",
  AI_INVALID_RESPONSE: "AI_INVALID_RESPONSE",
  AI_NOT_CONFIGURED: "AI_NOT_CONFIGURED",
  AI_RATE_LIMIT: "AI_RATE_LIMIT",
  AI_UNAVAILABLE: "AI_UNAVAILABLE",
  API_CAPABILITY_REQUIRED: "API_CAPABILITY_REQUIRED",
  CALENDAR_CONFLICT: "CALENDAR_CONFLICT",
  COMPLETED_ITEM: "COMPLETED_ITEM",
  DEADLINE_EXCEEDED: "DEADLINE_EXCEEDED",
  DURATION_TOO_SHORT: "DURATION_TOO_SHORT",
  FIXED_ITEM: "FIXED_ITEM",
  HABIT_REST_DAY: "HABIT_REST_DAY",
  IMPORT_ARCHIVE_INVALID: "IMPORT_ARCHIVE_INVALID",
  IMPORT_ARCHIVE_TOO_LARGE: "IMPORT_ARCHIVE_TOO_LARGE",
  INSUFFICIENT_CAPACITY: "INSUFFICIENT_CAPACITY",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INTERRUPTED: "INTERRUPTED",
  INVALID_INTERVAL: "INVALID_INTERVAL",
  INVALID_TASK_PLAN: "INVALID_TASK_PLAN",
  ITEM_CREATE_REQUEST_CONFLICT: "ITEM_CREATE_REQUEST_CONFLICT",
  ITEM_HAS_OPEN_SUBTASKS: "ITEM_HAS_OPEN_SUBTASKS",
  ITEM_NOT_FOUND: "ITEM_NOT_FOUND",
  ITEM_PARENT_CONFLICT: "ITEM_PARENT_CONFLICT",
  ITEM_VERSION_CONFLICT: "ITEM_VERSION_CONFLICT",
  NETWORK_ERROR: "NETWORK_ERROR",
  NOTE_NOT_FOUND: "NOTE_NOT_FOUND",
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  NOT_FOUND: "NOT_FOUND",
  OCCURRENCE_REQUIRED: "OCCURRENCE_REQUIRED",
  ORIGIN_NOT_ALLOWED: "ORIGIN_NOT_ALLOWED",
  OUTSIDE_RANGE: "OUTSIDE_RANGE",
  OUTSIDE_WORK_WINDOW: "OUTSIDE_WORK_WINDOW",
  OVERLAP: "OVERLAP",
  PAST_SCHEDULE: "PAST_SCHEDULE",
  PROJECT_AI_SESSION_MISSING: "PROJECT_AI_SESSION_MISSING",
  PROJECT_AI_STALE: "PROJECT_AI_STALE",
  PROJECT_TASK_NOT_RECOMMENDED: "PROJECT_TASK_NOT_RECOMMENDED",
  RECURRENCE_DATE: "RECURRENCE_DATE",
  RECURRENCE_LOCAL_TIME_INVALID: "RECURRENCE_LOCAL_TIME_INVALID",
  RECURRENCE_REQUEST_CONFLICT: "RECURRENCE_REQUEST_CONFLICT",
  RESTORED_WORKSPACE: "RESTORED_WORKSPACE",
  REVIEW_SUGGESTION_UNAVAILABLE: "REVIEW_SUGGESTION_UNAVAILABLE",
  SERIES_VERSION_CONFLICT: "SERIES_VERSION_CONFLICT",
  SNOOZE_REQUEST_CONFLICT: "SNOOZE_REQUEST_CONFLICT",
  TASK_PLAN_ALREADY_CONFIRMED: "TASK_PLAN_ALREADY_CONFIRMED",
  TASK_PLAN_BLOCKED: "TASK_PLAN_BLOCKED",
  TASK_PLAN_CONTEXT_PERMISSION: "TASK_PLAN_CONTEXT_PERMISSION",
  TASK_PLAN_NOT_CONFIRMABLE: "TASK_PLAN_NOT_CONFIRMABLE",
  TASK_PLAN_NOT_EDITABLE: "TASK_PLAN_NOT_EDITABLE",
  TASK_PLAN_NOT_FOUND: "TASK_PLAN_NOT_FOUND",
  TASK_PLAN_REQUEST_CONFLICT: "TASK_PLAN_REQUEST_CONFLICT",
  TASK_PLAN_REVISION_CONFLICT: "TASK_PLAN_REVISION_CONFLICT",
  TASK_PLAN_STALE: "TASK_PLAN_STALE",
  TASK_PLAN_TYPE_CONFLICT: "TASK_PLAN_TYPE_CONFLICT",
  TASK_PLAN_VERIFY_FAILED: "TASK_PLAN_VERIFY_FAILED",
  TASK_SERIES_NOT_FOUND: "TASK_SERIES_NOT_FOUND",
  TASK_SERIES_RELATION_NOT_FOUND: "TASK_SERIES_RELATION_NOT_FOUND",
  UNKNOWN_DURATION: "UNKNOWN_DURATION",
  UNSCHEDULED_WORK: "UNSCHEDULED_WORK",
  USER_LOCKED: "USER_LOCKED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  VERSION_CONFLICT: "VERSION_CONFLICT",
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

// 服务端只应返回表内的码（类型层面已由 ErrorCode 保证），但网络另一侧
// 仍可能送来意外值，所以边界处用它校验一次而不是直接断言。
export const errorCodeSchema = z.enum(Object.keys(ERROR_CODES) as [ErrorCode, ...ErrorCode[]])
